### ISSUE TITLE
视频清晰度问题

### ISSUE THREAD

**Issue by KennyLiu25775** [HeLiangHIT/douyin_downloader#6]
你好 这个爬虫爬下来的视频好像清晰度有损 一般的都是1280X720的 但是我下载下来的很多视频都是比这个低。。。

**Comment by KennyLiu25775** [comment]
![image](https://user-images.githubusercontent.com/11808716/51224838-a6c0f700-18fc-11e9-93e8-2c928c467b5c.png)
左边是我用抖音下载下来的 右边是用这个爬虫软件下载下来的 谢谢

**Comment by KennyLiu25775** [comment]
![image](https://user-images.githubusercontent.com/11808716/51225696-8e52db80-1900-11e9-8b53-5aa5869789b8.png)
右边是手机直接下载下来的 左边是用这个爬虫爬下来的

**Comment by HeLiangHIT** [comment]
话说你不说我到没注意我这个下载下来的居然是没有logo的～清晰度我觉得不是很重要吧，下载速度才是我关注的问题。

**Comment by KennyLiu25775** [comment]
谢谢你的回复，是的 你的这个爬虫是自动去水印的很棒 而且下载速度在几个抖音爬虫的比起来算挺快的 其实1280X720P 和  1024X576P的差别还可以接受 但主要是我们最后会对下载的视频做一些后期处理和压制 处理过后的视频质量会在这个基础上又降低级 所以如果能够做到下载的时候无损那就最好了 这个是另外一个我用过的抖音爬虫https://github.com/Jack-Cherish/python-spider/tree/master/douyin 他们的视频下载下来是无损的 但是经常会存在下载问题  如果你感兴趣可以看看 我觉得现在抖音爬虫其实也挺多的 但是如果有一款能做到除水印 下载快 又无损视频质量的 一定会受到最多的欢迎的 :)

**Comment by HeLiangHIT** [comment]
简单的看了一下，原理上好像是差不多的，都是取了返回json里面的aweme_list.video.url_list里面的地址来下载视频，他的代码里只取了第一个，我会遍历所有的地址依次尝试下载。不过他进一步将下载地址里面的playwm换成了play，参考如下：
```
		if watermark_flag == True:
			download_url = video_url
		# 无水印视频
		else:
			download_url = video_url.replace('playwm', 'play')
```
如果你有这个需求的话可以尝试自己修改一下： douyin_tool.py 229 行 改为
```
            url_list = play_addr_raw[0:2]
            return [url.replace('playwm', 'play') for url in url_list]
```
这个工程暂时就不改了～

**Comment by KennyLiu25775** [comment]
好的 谢谢你~ 我去试试看
